on:
  push:
    branches:
      - main
      - create-exe
      - 213-executable

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest", "macos-latest"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
          
      # Only run this on macOS as brew isn't available on Windows
      - run: brew install mysql pkg-config portaudio
        if: ${{ matrix.os == 'macos-latest' }}
        
      - run: python -m pip install --upgrade pip
      - run: pip install --upgrade wheel
      - run: pip install -r requirements.txt pyinstaller importlib-metadata sacremoses tokenizers
      
      # Uninstalling typing for compatibility with Python 3.11
      - run: pip uninstall -y typing
      
      # Modify PyInstaller command to include additional data
      - run: |
          pyinstaller --noconfirm --noconsole --onedir -c \
            --copy-metadata tqdm \
            --copy-metadata regex \
            --copy-metadata sacremoses \
            --copy-metadata requests \
            --copy-metadata packaging \
            --copy-metadata filelock \
            --copy-metadata tokenizers \
            --copy-metadata importlib_metadata \
            --collect-data sv_ttk \
            --hidden-import "babel.numbers" \
            --add-data "shared/images/*:shared/images" \
            --add-data "shared/sounds/*:shared/sounds" \
            --add-data "settings/serial ports/*:settings/serial ports" \
            main.py

      # Rename the executable on Windows for clarity
      - shell: cmd
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          ren dist\main\main.exe Mouser.exe

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Mouser_${{ matrix.os }}
          path: dist/main/*
